# Generated by Django 4.1.1 on 2022-09-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract",
            field=models.FileField(blank=True, null=True, upload_to="contracts"),
        ),
    ]
