# Generated by Django 4.1.1 on 2022-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_contract"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="contract",
            options={"ordering": ("end_date",)},
        ),
        migrations.AlterModelOptions(
            name="ministry",
            options={"verbose_name_plural": "ministries"},
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract",
            field=models.FileField(
                blank=True,
                default="default_contract.pdf",
                null=True,
                upload_to="contracts",
            ),
        ),
    ]
