# Generated by Django 4.1.1 on 2022-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_category_options_alter_contract_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(),
        ),
    ]
