# Generated by Django 4.1.1 on 2022-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_alter_contract_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"ordering": ("-end_date",)},
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_ended",
            field=models.BooleanField(default=False),
        ),
    ]
