# Generated by Django 4.1.2 on 2022-10-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_remove_contract_contract_ended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
